services:
  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    ports:
      - "3001:3001"
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    ports:
      - "5000:5000"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: unipi
      POSTGRES_USER: uniPiAdmin
      POSTGRES_PASSWORD: Esiakpene10!
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./packages/backend/init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh:ro
volumes:
  redis-data:
  postgres-data: