version: '3'
services:
  frontend:
    build: ./packages/frontend
    ports:
      - "3000:3000"
  backend:
    build: ./packages/backend
    ports:
      - "5000:5000"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: unipi
      POSTGRES_USER: uniPiAdmin
      POSTGRES_PASSWORD: Esiakpene10!